name: Build Wails App
on:
  workflow_dispatch:
    inputs:
      go-version:
        required: false
        type: string
        default: '1.23.6'
      node-version:
        required: false
        type: string
        default: '22.x'
      wails-version:
        required: false
        type: string
        default: 'v2.9.2'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: linux
            artifact_name: app-linux
          - os: windows-latest
            platform: windows
            artifact_name: app-windows
          - os: macos-latest
            platform: darwin
            artifact_name: app-macos
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          
      - name: Install Linux Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@${{ inputs.wails-version }}
        
      - name: Build Frontend
        working-directory: frontend
        run: |
          npm install
          npm run build
          
      - name: Build Wails App (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: |
          wails build -platform ${{ matrix.platform }}/amd64
          
      - name: Build Wails App (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          wails build -platform ${{ matrix.platform }}/amd64 -nsis
          
      - name: Upload Artifacts (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: build/bin/*
          
      - name: Upload Artifacts (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            build/bin/*.exe
            build/bin/*.msi
            
      - name: Upload Artifacts (macOS)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            build/bin/*.app
            build/bin/*.dmg